# Config file for automatic testing at travis-ci.org
language: python
env:
- FLASK_APP=comhina.py FLASK_DEBUG=1
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r requirements/dev.txt
  - nvm install 6.10
  - nvm use 6.10
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint
script: flask test
